version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:8089" # Мапинг портов: локальный порт 8080 -> контейнерный порт 80
    restart: always